#pragma once

#include <array>
#include <string>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <cstring>
#include <cuda_runtime_api.h>
#include <NvInfer.h>

#include "../bootstrap/GameConfig.hpp"
#include "../util/AlignedVec.hpp"

namespace Core
{
    // ========================================================================
    // CUDA ERROR CHECKING MACRO
    // ========================================================================
#define CUDA_CHECK(call) \
        do { \
            cudaError_t err = call; \
            if (err != cudaSuccess) { \
                std::cerr << "[CUDA Error] " << __FILE__ << ":" << __LINE__ << " - " \
                          << cudaGetErrorString(err) << std::endl; \
                std::terminate(); \
            } \
        } while (0)

    // ========================================================================
    // TENSORRT LOGGER
    // ========================================================================
    class TRTLogger : public nvinfer1::ILogger {
    public:
        void log(Severity severity, const char* msg) noexcept override {
            // Only log Warnings and Errors to keep the console clean during Self-Play
            if (severity <= Severity::kWARNING) {
                std::cerr << "[TensorRT] " << msg << std::endl;
            }
        }
    };
    inline static TRTLogger g_logger;

    // ========================================================================
    // MODEL RESULTS
    // ========================================================================
    template<ValidGameTraits GT>
    struct ModelResultsT
    {
        USING_GAME_TYPES(GT);
        std::array<float, Defs::kNumPlayers> values{};
        std::array<float, Defs::kActionSpace> policy{};

        ModelResultsT() noexcept = default;
    };

    // ========================================================================
    // NEURAL NET (TensorRT Asynchronous GPU Wrapper)
    // ========================================================================
    template<ValidGameTraits GT>
    class NeuralNet
    {
    private:
        USING_GAME_TYPES(GT);
        using ModelResults = ModelResultsT<GT>;

        int m_deviceId;
        uint32_t m_inferenceBatchSize;
        cudaStream_t m_stream;

        nvinfer1::IRuntime* m_runtime = nullptr;
        nvinfer1::ICudaEngine* m_engine = nullptr;
        nvinfer1::IExecutionContext* m_context = nullptr;

        // GPU Device Buffers
        float* d_nnInputBuffer = nullptr;
        float* d_nnOutputValues = nullptr;
        float* d_nnOutputPolicy = nullptr;

        // CPU Host Buffers (Pinned/Page-Locked Memory for ultra-fast PCIe DMA transfers)
        float* h_nnInputBuffer = nullptr;
        float* h_outputValues = nullptr;
        float* h_outputPolicy = nullptr;

        // --------------------------------------------------------------------
        // Deserializes the highly optimized .plan file generated by trtexec
        // --------------------------------------------------------------------
        void loadTensorRTEngine(const std::string& enginePath)
        {
            std::ifstream file(enginePath, std::ios::binary);
            if (!file.is_open()) {
                throw std::runtime_error("Fatal Error: Could not find or open TensorRT engine file at: " + enginePath);
            }

            file.seekg(0, file.end);
            size_t size = file.tellg();
            if (size == 0) {
                throw std::runtime_error("Fatal Error: TensorRT engine file is empty: " + enginePath);
            }
            file.seekg(0, file.beg);

            AlignedVec<char> trtModelStream(reserve_only, size);
            file.read(trtModelStream.data(), size);
            file.close();

            m_runtime = nvinfer1::createInferRuntime(g_logger);
            m_engine = m_runtime->deserializeCudaEngine(trtModelStream.data(), size);
            if (!m_engine) throw std::runtime_error("Fatal Error: Failed to deserialize CUDA engine.");

            m_context = m_engine->createExecutionContext();
            if (!m_context) throw std::runtime_error("Fatal Error: Failed to create Execution Context.");
        }

    public:
        NeuralNet(int deviceId, uint32_t inferenceBatchSize, const std::string& enginePath)
            : m_deviceId(deviceId), m_inferenceBatchSize(inferenceBatchSize)
        {
            CUDA_CHECK(cudaSetDevice(m_deviceId));
            CUDA_CHECK(cudaStreamCreate(&m_stream));

            loadTensorRTEngine(enginePath);

            // 1. Allocate GPU Memory
            CUDA_CHECK(cudaMalloc(&d_nnInputBuffer, inferenceBatchSize * Defs::kNNInputSize * sizeof(float)));
            CUDA_CHECK(cudaMalloc(&d_nnOutputValues, inferenceBatchSize * Defs::kNumPlayers * sizeof(float)));
            CUDA_CHECK(cudaMalloc(&d_nnOutputPolicy, inferenceBatchSize * Defs::kActionSpace * sizeof(float)));

            // 2. Allocate CPU Pinned Memory (Prevents OS paging, allows direct DMA)
            CUDA_CHECK(cudaMallocHost(&h_nnInputBuffer, inferenceBatchSize * Defs::kNNInputSize * sizeof(float)));
            CUDA_CHECK(cudaMallocHost(&h_outputValues, inferenceBatchSize * Defs::kNumPlayers * sizeof(float)));
            CUDA_CHECK(cudaMallocHost(&h_outputPolicy, inferenceBatchSize * Defs::kActionSpace * sizeof(float)));

            // 3. Bind Tensor Addresses (TensorRT V3 API requirement)
            m_context->setTensorAddress("input_state", d_nnInputBuffer);
            m_context->setTensorAddress("value_output", d_nnOutputValues);
            m_context->setTensorAddress("policy_output", d_nnOutputPolicy);
        }

        ~NeuralNet()
        {
            CUDA_CHECK(cudaSetDevice(m_deviceId));
            CUDA_CHECK(cudaStreamSynchronize(m_stream));
            CUDA_CHECK(cudaStreamDestroy(m_stream));

            cudaFree(d_nnInputBuffer);
            cudaFree(d_nnOutputValues);
            cudaFree(d_nnOutputPolicy);

            cudaFreeHost(h_nnInputBuffer);
            cudaFreeHost(h_outputValues);
            cudaFreeHost(h_outputPolicy);

            if (m_context) delete m_context;
            if (m_engine) delete m_engine;
            if (m_runtime) delete m_runtime;
        }

        // --------------------------------------------------------------------
        // BATCH INFERENCE
        // Receives fully encoded, contiguous memory from the ThreadPool
        // --------------------------------------------------------------------
        void forwardBatch(const AlignedVec<std::array<float, Defs::kNNInputSize>>& batchInputs,
            AlignedVec<ModelResults>& results)
        {
            int32_t batchSize = static_cast<int32_t>(batchInputs.size());
            if (batchSize == 0) return;

            if (results.size() < static_cast<size_t>(batchSize)) {
                results.resize(batchSize);
            }

            CUDA_CHECK(cudaSetDevice(m_deviceId));

            // =================================================================
            // 1. DYNAMIC SHAPE CONFIGURATION
            // =================================================================
            // TensorRT must be informed of the exact batch size before execution
            m_context->setInputShape("input_state", nvinfer1::Dims2{ batchSize, static_cast<int32_t>(Defs::kNNInputSize) });

            // =================================================================
            // 2. MEMORY TRANSFER (CPU -> GPU)
            // =================================================================
            size_t inputBytes = batchSize * Defs::kNNInputSize * sizeof(float);

            // Blazing fast contiguous copy from the AlignedVec to Pinned Memory
            std::memcpy(h_nnInputBuffer, batchInputs.data(), inputBytes);

            CUDA_CHECK(cudaMemcpyAsync(d_nnInputBuffer, h_nnInputBuffer, inputBytes, cudaMemcpyHostToDevice, m_stream));

            // =================================================================
            // 3. TENSORRT EXECUTION (Asynchronous)
            // =================================================================
            m_context->enqueueV3(m_stream);

            // =================================================================
            // 4. MEMORY TRANSFER (GPU -> CPU)
            // =================================================================
            size_t valueBytes = batchSize * Defs::kNumPlayers * sizeof(float);
            size_t policyBytes = batchSize * Defs::kActionSpace * sizeof(float);

            CUDA_CHECK(cudaMemcpyAsync(h_outputValues, d_nnOutputValues, valueBytes, cudaMemcpyDeviceToHost, m_stream));
            CUDA_CHECK(cudaMemcpyAsync(h_outputPolicy, d_nnOutputPolicy, policyBytes, cudaMemcpyDeviceToHost, m_stream));

            // Block CPU thread until the GPU finishes this specific stream
            CUDA_CHECK(cudaStreamSynchronize(m_stream));

            // =================================================================
            // 5. RESULT FORMATTING
            // =================================================================
            for (int32_t b = 0; b < batchSize; ++b)
            {
                auto& res = results[b];

                std::memcpy(res.values.data(), &h_outputValues[b * Defs::kNumPlayers], Defs::kNumPlayers * sizeof(float));
                std::memcpy(res.policy.data(), &h_outputPolicy[b * Defs::kActionSpace], Defs::kActionSpace * sizeof(float));
            }
        }
    };
}