import os
import sys
import yaml
import json
import argparse
import subprocess
import torch
from pathlib import Path

from train import OneMindArmyNet, export_to_onnx, compile_tensorrt_engine

def bootstrap_v0(config_path: str):
    """
    Resolves the "Chicken and Egg" Bootstrapping Paradox.

    Problem:
      - The C++ engine needs a TensorRT model to generate self-play data.
      - The PyTorch script needs C++ dimensions to build the model structure.
    
    Pipeline:
      1. Headless C++ execution extracts constexpr metadata (game dimensions).
      2. PyTorch constructs a randomized architecture matching those bounds.
      3. The initialized weights are saved (`latest_checkpoint.pt`) to anchor 
         the training loop to this exact starting state.
      4. The model is compiled into TensorRT (`best_model.plan`) so C++ can 
         begin the iteration 0 rollout.
    """
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)

    game_name     = config["name"]
    trt_opt_batch = config["backend"].get("inferenceBatchSize", 256)
    trt_precision = config["backend"].get("precision", "fp16").lower()

    print("=" * 60)
    print(f"  Bootstrapping v0 random model  —  game: [{game_name}]")
    print(f"  Batch: {trt_opt_batch}  |  Precision: {trt_precision.upper()}")
    print("=" * 60)

    # ------------------------------------------------------------------
    # 1. C++ Metadata Extraction
    # ------------------------------------------------------------------
    print("\n[Init] Calling C++ engine to export constexpr game dimensions...")

    exe_name = "onemindarmy.exe" if os.name == "nt" else "onemindarmy"
    possible_paths = [
        Path(f"build/x64-Release/bin/{exe_name}"),
        Path(f"build/bin/Release/{exe_name}"),
        Path(f"build/bin/{exe_name}"),
        Path(f"bin/{exe_name}"),
    ]

    cpp_executable = next((p for p in possible_paths if p.exists()), None)
    if not cpp_executable:
        print(f"\n[Fatal] C++ executable '{exe_name}' not found.")
        print("  Please compile the C++ project first.")
        sys.exit(1)

    try:
        subprocess.run(
            [str(cpp_executable), config_path, "--mode", "export-meta"],
            check=True,
        )
    except subprocess.CalledProcessError as e:
        print(f"\n[Fatal] C++ engine failed to export metadata (exit code {e.returncode}).")
        sys.exit(1)

    # ------------------------------------------------------------------
    # 2. Metadata Verification
    # ------------------------------------------------------------------
    data_dir  = Path(f"data/{game_name}")
    meta_path = data_dir / f"{game_name}_training_data.bin.meta.json"

    if not meta_path.exists():
        print(f"\n[Fatal] Expected meta file not found at: {meta_path}")
        sys.exit(1)

    print(f"\n[Init] Reading metadata from {meta_path} ...")
    with open(meta_path, "r") as f:
        meta = json.load(f)

    print(
        f"[Init] Dimensions: nnInputSize={meta['nnInputSize']}  "
        f"actionSpace={meta['actionSpace']}  "
        f"numPlayers={meta['numPlayers']}"
    )

    # ------------------------------------------------------------------
    # 3. Network Instantiation
    # ------------------------------------------------------------------
    model_dir = Path(f"models/{game_name}")
    model_dir.mkdir(parents=True, exist_ok=True)

    checkpoint_path = model_dir / "latest_checkpoint.pt"
    onnx_path       = model_dir / "latest_model.onnx"
    best_plan_path  = model_dir / "best_model.plan"

    print("\n[Init] Building PyTorch Transformer with random weights ...")
    model = OneMindArmyNet(config, meta)

    # ------------------------------------------------------------------
    # 4. Checkpoint Anchoring
    # Secures the randomized weights. If the training script generated a new 
    # random model upon starting, the data generated by the C++ engine (using 
    # the TRT export of THIS model) would be utterly disconnected from the 
    # gradients applied during training.
    # ------------------------------------------------------------------
    if checkpoint_path.exists():
        print(f"[Init] Checkpoint already exists at {checkpoint_path}. Skipping save to avoid overwrite.")
    else:
        torch.save(
            {
                "model":       model.state_dict(),
                "optimizer":   None,
                "global_step": 0,
                "iteration":   0,
            },
            checkpoint_path,
        )
        print(f"[Init] Checkpoint saved → {checkpoint_path}")

    # ------------------------------------------------------------------
    # 5. TensorRT Compilation
    # ------------------------------------------------------------------
    export_to_onnx(model, meta, str(onnx_path))
    compile_tensorrt_engine(
        str(onnx_path),
        str(best_plan_path),
        meta,
        trt_opt_batch,
        precision=trt_precision,
    )

    print(f"\n[Init] v0 bootstrap complete.")
    print(f"  Checkpoint : {checkpoint_path}")
    print(f"  TRT engine : {best_plan_path}")
    print("  You can now start the Orchestrator.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="OneMindArmy — v0 Bootstrapper")
    parser.add_argument("--config", type=str, required=True, help="Path to YAML config file")
    args = parser.parse_args()
    bootstrap_v0(args.config)